server:
  port: 8004

spring:
  config:
    import: classpath:/common.yml
  application:
    name: notification-service
app:
  notification:
    twilio:
      account-sid: ${TWILIO_ACCOUNT_SID:}
      auth-token: ${TWILIO_AUTH_TOKEN:}
      whatsapp-number: ${TWILIO_WHATSAPP_NUMBER:}
    email:
      from: noreply@school-management.com
      smtp-server: smtp.gmail.com

