server:
  port: 8004
  servlet:
    context-path: /

spring:
  application:
    name: notification-service
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/school_management?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout: 20000

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
app:
  base-url: http://192.168.1.10:8000/ui
  jwt-secret-key: mySecretKeyIsMoreSecureThanAnyOtherSecureApplicatoinOrKeyStore
  corsallowed:
    - "http://localhost:4200"
    - "http://192.168.1.10:8000"
  open-endpoints:
    - "/ui/**"
    - "/api/auth/**"
    - "/api/public/**"
    - "/internal/**"
    - "/v3/api-docs/**"
    - "/swagger-ui/**"
    - "/swagger-ui/index.html"
    - "/static/ui/**"
  jwt-expiration-ms: 86400000
  notification:
    twilio:
      account-sid: ${TWILIO_ACCOUNT_SID:}
      auth-token: ${TWILIO_AUTH_TOKEN:}
      whatsapp-number: ${TWILIO_WHATSAPP_NUMBER:}
    email:
      from: noreply@school-management.com
      smtp-server: smtp.gmail.com

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha
  api-docs:
    path: /v3/api-docs