server:
  port: 8003

spring:
  config:
    import: classpath:/common.yml
  application:
    name: payment-service
  payment:
    reminder:
      days-before-due: 3
      days-after-due: 7
      days-after-due-14: 14

