app:
  base-url: http://192.168.1.10:8000/ui
  jwt-secret-key: mySecretKeyIsMoreSecureThanAnyOtherSecureApplicatoinOrKeyStore
  corsallowed:
    - "http://localhost:4200"
    - "http://192.168.1.10:8000"
  open-endpoints:
    - "/ui/**"
    - "/api/auth/**"
    - "/api/public/**"
    - "/internal/**"
    - "/v3/api-docs/**"
    - "/swagger-ui/**"
    - "/swagger-ui.html"
    - "/swagger-ui/index.html"
    - "/webjars/**"
    - "/swagger-resources/**"
    - "/configuration/**"
    - "/favicon.ico"
    - "/static/ui/**"
  jwt-expiration-ms: 86400000